Repository tvkitchen/base, pull requests merged in 2020-05, with the labels that each got.

#16 Rename stream container data type
  docs/DATA_TYPES.md
  packages/constants/src/dataTypes.js
Labels: enhancement

#19 Fix payload deserialization
  packages/classes/src/Payload.js
  packages/classes/src/__test__/Payload.test.js
  packages/classes/src/__test__/__snapshots__/Payload.test.js.snap
Labels: bug

#23 Prepare repo for publishing to npm
  docs/CONTRIBUTING.md
  package.json
  packages/classes/CHANGELOG.md
  packages/classes/README.md
  packages/classes/package.json
  packages/constants/CHANGELOG.md
  packages/constants/README.md
  packages/constants/package.json
  packages/errors/CHANGELOG.md
  packages/errors/README.md
  packages/errors/package.json
  packages/interfaces/CHANGELOG.md
  packages/interfaces/README.md
  packages/interfaces/package.json
Labels: devops

#25 Publish v1.0.0 of all packages
  packages/classes/CHANGELOG.md
  packages/classes/package.json
  packages/constants/CHANGELOG.md
  packages/constants/package.json
  packages/errors/CHANGELOG.md
  packages/errors/package.json
  packages/interfaces/CHANGELOG.md
  packages/interfaces/package.json
Labels: devops

#26 Remove references to Lerna bootstrapping
  .travis.yml
  README.md
  package.json
Labels: devops

#27 Clean up ESLint configuration
  .eslintrc.json
  package.json
Labels: devops

#32 Add Travis CI badge to README
  README.md
Labels: enhancement
