Repository tvkitchen/base, pull requests merged in 2020-06, with the labels that each got.

#29 Add bug template
  .github/ISSUE_TEMPLATE/bug.md
Labels: documentation

#33 Fix CONTRIBUTING’s broken links and misinformation
  docs/CONTRIBUTING.md
Labels: documentation

#30 Add descriptions to all package.json files
  packages/classes/CHANGELOG.md
  packages/classes/package.json
  packages/constants/CHANGELOG.md
  packages/constants/package.json
  packages/errors/CHANGELOG.md
  packages/errors/package.json
  packages/interfaces/CHANGELOG.md
  packages/interfaces/package.json
Labels: enhancement

#35 Add time to Payload
  packages/classes/CHANGELOG.md
  packages/classes/README.md
  packages/classes/docs/PAYLOAD.md
  packages/classes/src/Payload.js
  packages/classes/src/__test__/Payload.test.js
  packages/classes/src/__test__/__snapshots__/Payload.test.js.snap
Labels: enhancement

#43 Add setup and teardown methods to IAppliance
  packages/interfaces/CHANGELOG.md
  packages/interfaces/src/IAppliance.js
  packages/interfaces/src/__test__/IAppliance.test.js
  packages/interfaces/src/__test__/classes/FullyImplementedAppliance.js
Labels: enhancement

#44 Update IAppliance invoke method
  packages/interfaces/CHANGELOG.md
  packages/interfaces/src/IAppliance.js
Labels: enhancement

#51 Add log level constants
  packages/constants/CHANGELOG.md
  packages/constants/docs/LOG_LEVELS.md
  packages/constants/src/__test__/logLevels.test.js
  packages/constants/src/index.js
  packages/constants/src/logLevels.js
Labels: devops, enhancement

#49 Add logger to IAppliance
  packages/interfaces/CHANGELOG.md
  packages/interfaces/package.json
  packages/interfaces/src/IAppliance.js
  packages/interfaces/src/__test__/IAppliance.test.js
Labels: enhancement

#46 Create PayloadArray class
  packages/classes/CHANGELOG.md
  packages/classes/README.md
  packages/classes/docs/PAYLOAD.md
  packages/classes/docs/PAYLOAD_ARRAY.md
  packages/classes/src/PayloadArray.js
  packages/classes/src/__test__/Payload.unit.test.js
  packages/classes/src/__test__/PayloadArray.unit.test.js
  packages/classes/src/__test__/__snapshots__/Payload.unit.test.js.snap
  packages/classes/src/index.js
  packages/classes/src/tools/utils/__test__/sortedArray.test.js
  packages/classes/src/tools/utils/sortedArray.js
Labels: enhancement
